if [[ -n "${ZPROF:-}" ]]; then
    zmodload zsh/zprof # 加载 zsh 性能分析模块
fi

bindkey -e
bindkey '^U' backward-kill-line # Ctrl+U 删除光标之前的所有字符

source $ZDOTDIR/envs.zsh
source $ZDOTDIR/alias.zsh
source $ZDOTDIR/proxy.zsh
source $ZDOTDIR/zinit.zsh
source $ZDOTDIR/fzf.zsh
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(atuin init zsh --disable-up-arrow)"
atuin config set db_path "$ATUIN_DB_PATH"

# Starship: transient prompt + no blank line on fresh terminal
# __starship_first_prompt=true
# __starship_has_blank_line=false
# precmd_starship() {
#     if [[ $__starship_first_prompt == true ]]; then
#         __starship_first_prompt=false
#         __starship_has_blank_line=false
#     else
#         echo
#         __starship_has_blank_line=true
#     fi
# }
# preexec_starship() {
#     if [[ $__starship_has_blank_line == false ]]; then
#         # No blank line above: only clear the status line
#         printf '\033[2A\033[2K\033[2B'
#     else
#         # Has blank line above: clear blank line + status line, preserve ❯ cmd
#         printf '\033[3A\033[2K\033[1B\033[2K\033[2B'
#     fi
# }
# precmd_functions+=(precmd_starship)
# preexec_functions+=(preexec_starship)

# conda
[[ -f $HOME/miniforge3/etc/profile.d/conda.sh ]] && source $HOME/miniforge3/etc/profile.d/conda.sh
[[ -d $HOME/.conda ]] && rm -rf $HOME/.conda

(( $+functions[_history_substring_search_config] )) && _history_substring_search_config

if [[ -n "${ZPROF:-}" ]]; then
    zprof > $XDG_CACHE_HOME/zsh/zprof.log # 生成 zsh 性能分析报告
fi
